device: auto
seed: 4
num_stacks: 1
layers:
  min: 1
  max: 20
num_layers: 20
wavelengths:
  start: 0.3
  end: 1.499
  steps: 1200
polarisation: s
thicknesses_bounds:
  min: 1.0e-09
  max: 1.0e-06
materials:
  substrate: M_Glass_Substrate
  air: M_Air
  thin_films:
  - M_Ti_HZ
  - M_Al
  - M_ZnS
  - M_Cr_HZ
  - M_Si_HZ
  - M_MgO
  - M_Au
  - M_Al2O3_HZ
  - M_Si3N4
  - M_HfO2
  - M_AlN
  - M_Ta2O5
  - M_SiO2_HZ
  - M_SiO2
  - M_Al2O3
  - M_ZnO
  - M_Ag_HZ
  - M_ZnS_HZ
  - M_ZnSe_HZ
  - M_Ni_HZ
  - M_ZnO_HZ
  - M_Cr
  - M_ZnSe
  - M_Fe2O3_HZ
  - M_Al_HZ
  - M_TiO2_HZ
  - M_Ge_2
  - M_HfO2_HZ
  - M_MgF2_HZ
  - M_Si
  - M_TiN
  - M_Ge_1
  - M_MgF2
  - M_Ge
  - M_TiO2
  - M_ITO
  - M_Ge_HZ
  - M_Ag
theta:
  start: 0.0
  end: 0.0
  steps: 1
air_pad: false
stratified_sampling: false
sampling: soft
material_embedding:
  data_file: data/material_embedding/materials.yaml
tolerance: 0.001
autoencoder:
  latent_dim: 128
  num_layers: 4
architecture: mlp
mlp:
  hidden_dims:
  - 128
  - 512
  - 64
cnn:
  channel_dims:
  - 32
  - 64
  - 3
  kernel_size: 3
rnn:
  encoder_dim: 64
  decoder_dim: 32
transformer:
  hidden_seq_len: 400
  d_model: 256
  num_layers: 7
  num_heads: 8
  dropout: 0.1
  d_ff: 512
  src_mask: true
  tgt_struct_mask: false
  tgt_caus_mask: true
training:
  guided_learning_rate: 0.0001
  free_learning_rate: 1.0e-06
  reg_weight: 0.0
  num_epochs: 100
  batch_size: 128
  dataset_size: 5000
  save_model: true
  evaluate: true
  guidance_schedule:
  - guidance: guided
    density: complete
    percent: 0.2
  - guidance: free
    density: complete
    percent: 0.2
  - guidance: guided
    density: masked
    percent: 0.2
  - guidance: free
    density: masked
    percent: 0.2
  - guidance: free
    density: explicit
    percent: 0.2
wandb:
  log: false
  sweep: false
  project: inverse-mirrors-nn
  config:
    architecture: transformer
    guided_learning_rate: 0.0001
    free_learning_rate: 0.01
    epochs: 200
    batch_size: 128
