device: auto
seed: 3
num_stacks: 1
layers:
  min: 1
  max: 7
wavelengths:
  start: 0.3
  end: 1.499
  steps: 1200
polarisation: s
thicknesses_bounds:
  min: 1.0e-09
  max: 1.0e-06
materials:
  substrate: DC_Substrate
  air: DC_Air
  thin_films:
  - H
  - L
  - A
  - F
  - M
  - T
  - Ag
  - Au
  - Ni
theta:
  start: 0.0
  end: 0.0
  steps: 1
air_pad: true
stratified_sampling: true
num_layers: 7
material_embedding:
  data_file: data/material_embedding/materials.yaml
  dim: 2
  num_epochs: 200
  learning_rate: 0.01
tolerance: 0.001
architecture: mlp
transformer:
  model_dim: 16
  num_heads: 4
  num_layers: 5
  d_ff: 1024
  dropout: 0.1
training:
  guided_learning_rate: 0.0001
  free_learning_rate: 1.0e-05
  num_epochs: 500
  batch_size: 32
  dataset_size: 5000
  save_model: false
  evaluate: true
  guidance_schedule:
  - guidance: guided
    density: complete
    percent: 0.5
  - guidance: guided
    density: masked
    percent: 0.5
wandb:
  log: true
  project: inverse-mirrors-nn
  config:
    architecture: mlp
    guided_learning_rate: 0.0001
    free_learning_rate: 0.01
    epochs: 500
    batch_size: 32
