device: auto
seed: null
num_stacks: 1
layers:
  min: 1
  max: 5
num_layers: 5
wavelengths:
  start: 0.3
  end: 1.499
  steps: 1200
polarisation: s
thicknesses_max: 0.5
materials:
  substrate: M_Glass_Substrate
  air: M_Air
  thin_films:
  - M_Ti_HZ
  - M_Al
  - M_ZnS
  - M_Cr_HZ
  - M_Si_HZ
  - M_MgO
  - M_Au
  - M_Al2O3_HZ
  - M_Si3N4
  - M_HfO2
  - M_AlN
  - M_Ta2O5
  - M_SiO2_HZ
  - M_SiO2
  - M_Al2O3
  - M_ZnO
  - M_Ag_HZ
  - M_ZnS_HZ
  - M_ZnSe_HZ
  - M_Ni_HZ
  - M_ZnO_HZ
  - M_Cr
  - M_ZnSe
  - M_Fe2O3_HZ
  - M_Al_HZ
  - M_TiO2_HZ
  - M_Ge_2
  - M_HfO2_HZ
  - M_MgF2_HZ
  - M_Si
  - M_TiN
  - M_Ge_1
  - M_MgF2
  - M_Ge
  - M_TiO2
  - M_ITO
  - M_Ge_HZ
  - M_Ag
theta:
  start: 0.0
  end: 0.0
  steps: 1
air_pad: false
stratified_sampling: true
material_embedding:
  data_file: data/material_embedding/materials.yaml
tolerance: 0.001
sequential:
  beam_size: 3
architecture: transformer
mlp:
  hidden_dims:
  - 32
  - 128
  - 64
  - 256
  - 64
  - 128
  - 32
cnn:
  channel_dims:
  - 32
  - 64
  - 128
  - 64
  - 32
  kernel_size: 3
rnn:
  d_model: 128
  encoder_dims:
  - 64
  - 32
  - 64
  decoder_dims:
  - 128
  - 256
transformer:
  hidden_seq_len: 500
  d_model: 128
  num_layers: 4
  num_heads: 8
  dropout: 0.1
  d_ff: 512
  tgt_struct_mask: true
  tgt_caus_mask: true
  downsize: max # allowed values: sample, window, mean, max, conv
training:
  learning_rate: 1.0e-04
  learning_rate_end_factor: 0.3
  thicknesses_factor: 0.5
  constraint_factor: 0.5
  guided_factor: 10.5
  reg_weight: 0.0
  num_epochs: 100
  batch_size: 256
  dataset_size: 5000
  save_model: true
  evaluate: true
  curriculum:
  - density: complete
    percent: 0.2
  - density: masked
    percent: 0.2
  - density: explicit
    percent: 0.2
wandb:
  log: false
  sweep: false
  project: inverse-mirrors-nn
  config:
    architecture: transformer
    learning_rate: 1.0e-04
    epochs: 200
    batch_size: 128
