device: 'auto' # accepted values: "auto", "cpu"

seed: 0

num_stacks: 1

layers:
  min: 3
  max: &max_layers 13

wavelengths:
  start: 300.e-9
  end: 1100.e-9
  steps: 1000

thicknesses_bounds:
  min: 1.e-9
  max: 1.e-6

refractive_indices_bounds:
  min: 0.12
  max: 2.25

theta:
  start: 0
  end: 0
  steps: 1

num_layers: *max_layers

material_embedding:
  data_file: "data/material_embedding/materials.yaml"
  dim: 2
  num_epochs: 10000
  learning_rate: 0.01

tolerance: 1.0e-3

scaling:
  thicknesses: 1.0e+6
  refractive_indices: 0.1

architecture:
  relaxed: &architecture "mlp" # accepted values: "gradient", "mlp", "cnn"
  discretiser: "b&b" # accepted values: "rounder", "b&b"

training:
  learning_rate: &lr 0.001 # default: 0.001
  num_epochs: &epochs 10
  batch_size: &batch_size 50
  guidance: &guidance "free" # accepted values: "free", "guided"
  dataset_switching: false
  dataset_size: 100
  evaluate: true

data_generation:
  density: "complete" # accepted values: "complete", "masked", "explicit"
  guidance: *guidance
  dataset_size: 100

branch_and_bound:
  max_iter: 300

wandb_log: false

wandb:
  project: "inverse-mirrors-nn"
  config:
    architecture: *architecture
    learning_rate: *lr
    epochs: *epochs
    batch_size: *batch_size