device: auto
seed: null
num_stacks: 1
layers:
  min: 1
  max: 7
wavelengths:
  start: 0.3
  end: 1.499
  steps: 1200
polarisation: s
thicknesses_bounds:
  min: 1.0e-09
  max: 1.0e-06
materials:
  substrate: DC_Substrate
  air: DC_Air
  thin_films:
  - H
  - L
  - A
  - F
  - M
  - T
  - Ag
  - Au
  - Ni
theta:
  start: 0.0
  end: 0.0
  steps: 1
air_pad: true
stratified_sampling: false
num_layers: 7
material_embedding:
  data_file: data/material_embedding/materials.yaml
  dim: 2
tolerance: 0.001
architecture: transformer
transformer:
  hidden_seq_len: 500
  d_model: 64
  num_layers: 5
  num_heads: 8
  dropout: 0.1
  d_ff: 1024
  src_mask: true
  tgt_struct_mask: true
  tgt_caus_mask: true
training:
  guided_learning_rate: 0.0001
  free_learning_rate: 1.0e-05
  num_epochs: 500
  batch_size: 3
  dataset_size: 5000
  save_model: false
  evaluate: true
  guidance_schedule:
#  - guidance: guided
#    density: complete
#    percent: 0.25
#  - guidance: free
#    density: complete
#    percent: 0.25
#  - guidance: guided
#    density: masked
#    percent: 0.25
#  - guidance: free
#    density: masked
#    percent: 0.25
  - guidance: free
    density: explicit
    percent: 1.0
wandb:
  log: false
  project: inverse-mirrors-nn
  config:
    architecture: transformer
    guided_learning_rate: 0.0001
    free_learning_rate: 0.01
    epochs: 500
    batch_size: 128
