device: 'auto' # accepted values: "auto", "cpu"

seed: null # <value> or null

num_stacks: 1

layers:
  min: 1 # must be >= 1
  max: &max_layers 50

wavelengths:
  start: 100.e-3
  end: 1499.e-3
  steps: 1400

polarisation: 's' # accepted values: "s", "p"

thicknesses_bounds:
  min: 1.e-9
  max: 1.e-6

materials:
  substrate: "DC_Substrate" # accepted values: "Suprasil Heraeus", "Suprasil", "BK7", "DC_Substrate"
  air: "DC_Air" # accepted values: "Air", "DC_Air"
  thin_films:
#    - "SiO2 IBS"
#    - "TiO2 IBS"
    - "H"
    - "L"
    - "A"
    - "F"
    - "M"
    - "T"
    - "Ag"
    - "Au"
    - "Ni"

theta:
  start: 0.
  end: 0.
  steps: 1

num_layers: *max_layers

material_embedding:
  data_file: "data/material_embedding/materials.yaml"
  dim: 2
  num_epochs: 200
  learning_rate: 0.01

tolerance: 1.0e-3

architecture: &architecture "transformer" # accepted values: "gradient", "mlp", "cnn", "transformer"

transformer:
  model_dim: 4
  num_heads: 1
  num_layers: 2
  d_ff: 4
  dropout: 0.1

training:
  learning_rate: &lr 0.0005 # default: 0.001
  num_epochs: &epochs 100
  batch_size: &batch_size 30
  guidance: &guidance "free" # accepted values: "free", "guided"
  dataset_switching: false
  dataset_size: 100
  save_model: false
  evaluate: true

data_generation:
  density: "complete" # accepted values: "complete", "masked", "explicit"
  guidance: *guidance
  dataset_size: 5000
  partition: "training" # accepted values: "training", "validation"

wandb:
  log: false
  project: "inverse-mirrors-nn"
  config:
    architecture: *architecture
    learning_rate: *lr
    epochs: *epochs
    batch_size: *batch_size
